# Generated by Django 2.2 on 2022-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0, verbose_name='Cholesterol (mg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Morning Snack'), (3, 'Lunch'), (4, 'Afternoon Snack'), (5, 'Dinner'), (6, 'Evening Snack')], verbose_name='Meal Time'),
        ),
    ]
