# Generated by Django 2.2 on 2022-08-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220827_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=0, verbose_name='Dietary Fibre (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=2, verbose_name='Protein (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=1, verbose_name='Sodium (mg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=10, verbose_name='Sugar (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbohydrate',
            field=models.FloatField(default=100, verbose_name='Total Carbohydrate (g)'),
            preserve_default=False,
        ),
    ]
